### ISSUE TITLE
Snake Working

### ISSUE THREAD

**Issue by pgawde1** [JiayouQin/project-02#4]
Snake implementation is incorrect.

Snake cant and shouldn't kill Captain. But snake can harm Captain by stealing his points and then spawning again at random location.(check project requirement PDF).

Snake can only kill Rabbits and spend 5 ticks sleeping after eating rabbit.

Game gets over only and only when Veggies are finished.(check sample output).

**Comment by JiayouQin** [comment]
Resolved
